[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
opacity = 1.0

[window.padding]
x = 10
y = 10

