[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[terminal.shell]
program = "/usr/bin/fish"


[window.padding]
x = 1
y = 1

[terminal]

# Default colors
[colors.primary]
background = '#041419'
foreground = '#697A82'

# Normal colors
[colors.normal]
black   = '#163541'
red     = '#CB4239'
green   = '#89982E'
yellow  = '#AE8B2D'
blue    = '#4689CC'
magenta = '#C34480'
cyan    = '#519F98'
white   = '#FCF6E5'

# Bright colors
[colors.bright]
black   = '#A1ACAD'
red     = '#F1A19E'
green   = '#DEFEB5'
yellow  = '#FBEAA3'
blue    = '#B4DBFC'
magenta = '#EE7FB7'
cyan    = '#C8FDF9'
white   = '#FFFFFF'

[window]
decorations = "full"
opacity = 0.9
